server.port=8084
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.forward-headers-strategy=framework


#Three lines below only runs when started in IDE, if started through docker, the environment variables gets injected into Spring automatically.
spring.datasource.url=jdbc:mysql://localhost:3306/${database_name:user}
spring.datasource.username=${database_username:root}
spring.datasource.password=${database_password:rootpassword}

# GitHub Login
spring.security.oauth2.client.registration.github.client-id=${GITHUBCLIENTID:dummy_github_client_id}
spring.security.oauth2.client.registration.github.client-secret=${GITHUBCLIENTSECRET:dummy_github_client_secret}

# Google Login

spring.security.oauth2.client.registration.google.client-id=${GOOGLECLIENTID:dummy_google_client_id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLECLIENTSECRET:dummy_google_client_secret}

# JWT Secret key

app.jwt.secret=${JWT_SECRET:en_superhemlig_default_nyckel_som_ar_minst_32_tecken_lang}
booking.service.url=${BOOKING_SERVICE_URL:http://localhost:8083}


logging.level.org.springframework.security=TRACE

spring.profiles.active=dev